### ISSUE TITLE
Rubocop: Empty class

### ISSUE THREAD

**Issue by triszt4n** [kir-dev/warp-next#60]
`SecureBlobExtension` is an empty class, because it is not used, but caused Zeitwerk issue if it wasn't defined there:

```
022-02-05T19:37:30.054778785Z => Booting Puma
2022-02-05T19:37:30.054857147Z => Rails 6.1.4 application starting in production 
2022-02-05T19:37:30.054868881Z => Run `bin/rails server --help` for more startup options
2022-02-05T19:37:30.263993503Z Exiting
2022-02-05T19:37:30.264180189Z /usr/local/bundle/gems/zeitwerk-2.4.2/lib/zeitwerk/loader/callbacks.rb:18:in `on_file_autoloaded': expected file /warp-next/app/extensions/secure_blob_extension.rb to define constant SecureBlobExtension, but didn't (Zeitwerk::NameError)
2022-02-05T19:37:30.264214761Z 	from /usr/local/bundle/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:38:in `block in require'
2022-02-05T19:37:30.264226564Z 	from <internal:kernel>:90:in `tap'
2022-02-05T19:37:30.264267282Z 	from /usr/local/bundle/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
2022-02-05T19:37:30.264279085Z 	from /warp-next/config/application.rb:42:in `block (2 levels) in <class:Application>'
2022-02-05T19:37:30.264289701Z 	from <internal:dir>:134:in `glob'
2022-02-05T19:37:30.264302203Z 	from /warp-next/config/application.rb:41:in `block in <class:Application>'
2022-02-05T19:37:30.264312469Z 	from /usr/local/bundle/gems/activesupport-6.1.4/lib/active_support/callbacks.rb:427:in `instance_exec'
...
```

**Comment by triszt4n** [comment]
Solved in another PR
